CREATE TABLE STUDENT_DEATIL(
    ENROLLMENT_NO  VARCHAR(25),
    NAME VARCHAR(25),
    CPI  DECIMAL(5,2),
    BIRTHDY  DATETIME
);

SELECT *FROM STUDENT_DEATIL

-- 1.Add two more columns City VARCHAR (20) (Not null) and Backlog INT (Null).

ALTER TABLE STUDENT_DEATIL
ADD CITY VARCHAR(20),
    BACKLOG INT

-- 2.Add column department VARCHAR (20) Not Null.

ALTER TABLE STUDENT_DEATIL
ADD DEPARTMENT VARCHAR(25) NOT NULL
SELECT *from STUDENT_DEATIL

-- 3.Change the size of NAME column of student_detail from VARCHAR (25) to VARCHAR (35).

ALTER TABLE STUDENT_DEATIL
ALTER COLUMN NAME VARCHAR(35)

-- 4.Change the data type DECIMAL to INT in CPI Column.

ALTER TABLE STUDENT_DEATIL
ALTER COLUMN CPI INT
SELECT *from STUDENT_DEATIL

-- 5.Delete Column City from the student_detail table.

ALTER TABLE STUDENT_DEATIL
DROP COLUMN CITY

-- 6. Rename Column Enrollment

SP_RENAME 'STUDENT_DEATIL.ENROLLMENT_NO','ENROLLMENT'

-- 7. Change name of table student_detail to STUDENT_MASTER.

SP_RENAME 'STUDENT_DEATIL','STUDENT_MASTER'
