-- 1.Rename Column ADATE to AOPENDATE OF DEPOSIT_DETAIL table.

SP_RENAME 'DEPOSIT_DETAIL.ADATE','AOPENDATE'
SELECT *from DEPOSIT_DETAIL

-- 2.Delete Column AOPENDATE from the DEPOSIT_DETAIL table.

ALTER TABLE DEPOSIT_DETAIL
DROP COLUMN AOPENDATE

-- 3.Rename Column CNAME to CustomerName.

SP_RENAME 'DEPOSIT_DETAIL.CNAME' , 'CUSTOMERNAME'

-- 4. Add Column country.
ALTER TABLE DEPOSIT_DETAIL 
ADD COUNTRY VARCHAR(50)
SELECT *from DEPOSIT_DETAIL